---
language_code: en-US

brand:
  image_uri: assets/LogoBrand-Horizontal-20230501.svg
  asset_uri: https://crosscompute.com

title_text: CrossCompute - Deploy Servers, Upload Tools, Control Access

description_text: Don't Let Hackers Wreak Havoc on Your Customers! Deploy Your Tools on Secure Private Servers. CrossCompute is a customizable platform for running tools. Our SDK and platform simplify the process of distributing web-based tools, with a focus on access security.

headline_text: Don't Let Hackers Wreak Havoc on Your Customers!

pitch_text: Deploy Your Tools on Secure Private Servers

pitch_markdown: |

  CrossCompute is a customizable platform for running tools. Our products simplify the distribution of analytical tools and APIs, focusing on access security.

updates:
  - name_text: 20260903 CrossCompute Platform 5.3.1 Release Notes
    description_text: Launch your own private instance of our CrossCompute Platform + Power Manager Kit (Electric Distribution Outage Statistics for Operations Managers).
    asset_uri: https://forum.crosscompute.com/t/crosscompute-platform-updates/226/2
  - name_text: 20260312 Electric Distribution Outage Statistics for Operations Managers
    description_text: Use historical data to see where, when and why unplanned outages are happening.
    asset_uri: https://forum.crosscompute.com/t/electric-distribution-outage-statistics-for-operations-managers/245
    extra_html: <div class="_spotlight"><img class="_hidden" loading="lazy" data-src="https://forum.crosscompute.com/uploads/default/original/1X/cb1290f4765815c2e464b78175a5ae6952d814db.gif"></div>

links:
  - name_text: Forum
    description_text: Answers to questions
    asset_uri: https://forum.crosscompute.com
  - name_text: YouTube
    description_text: Updates and demos
    asset_uri: https://www.youtube.com/crosscompute
  - name_text: GitHub
    description_text: Our code repositories
    asset_uri: https://github.com/crosscompute
