---
pages:
  - id: index
    title: CrossCompute
    description:
      path: page-index.txt
posts:
  - title: Simplify Outage Tracking
    description:
      path: post-simplify-outage-tracking-20220711.md
  - title: Webify Your Scripts into Report Products
    description:
      path: post-script-webification-20220512.md
  - title: Apply to List Your Profile in Our Upcoming Computational Marketplace
    description:
      path: post-computational-marketplace-20220426.md
  - title: CrossCompute Framework 0.9.2.3 Release Notes
    description:
      path: post-crosscompute-0.9.2.3.md
  - title: CrossCompute Framework 0.9.1.4 Release Notes
    description:
      path: post-crosscompute-0.9.1.4.md
    timestamp: 20220311-1313
  - title: Analytics Content 2022-02
    description:
      path: post-analytics-content-202202.md
    timestamp: 20220310-1919
  - title: Lightweight Architecture for Analytics Automation
    description:
      path: post-lightweight-architecture.md
    timestamp: 20220307-1400
  - title: Open Call for Runnable Reports
    description:
      path: post-open-call-for-runnable-reports.md
    timestamp: 20210525-0140
