---
language_code: en-US

brand:
  image_uri: assets/LogoBrand-Horizontal-20230501.svg
  asset_uri: https://crosscompute.com

title_text: CrossCompute - Create and Share Runnable Tools

description_text: Create and share runnable tools across your organization. CrossCompute is a customizable platform for running engineering and utility project planning tools. Our software development kit and platform simplify the process of developing and distributing web-based, runnable tools. Our solution is specialized for deploying decision support tools in scenario planning, electricity infrastructure and hazard mitigation.

headline_text: Create and Share Runnable Tools

pitch_text: Specialized for Scenario Planning, Electricity Infrastructure and Hazard Mitigation

pitch_markdown: |

  Do you find yourself analyzing the same datasets to answer the same questions over and over?

  Turn your task into a runnable, web-based tool!

  - CrossCompute is a customizable platform for running engineering and utility project planning tools.
  - Our SDK and platform simplify the process of developing and distributing web-based tools.

  Share runnable tools across your organization by launching a private deployment of our platform.

updates:
  - name_text: Suggest a Tool
    description_text: CrossCompute Platform 5.0.0 is now live! What tools would you like to see? We are in the process of porting tools from the earlier versions 1 through 4, which we estimate will take most of this year to complete. You can also use the form if you would like to make your tools available on the platform.
    asset_uri: https://crosscompute.com/t/suggest-tool
  - name_text: Launch Machine for Pair Programming Command Line
    description_text: Start a pair programming session in a secure sandbox. Thank you to Abdourahamane Issaka Sani, Rohan Sazad, Tam Nguyen for your work on this tool.
    asset_uri: https://crosscompute.com/t/pair-program
  - name_text: Try CrossCompute Platform 4
    description_text: CrossCompute Platform 4 was completed in 2023 and featured tools for testing our CrossCompute Analytics SDK, including our custom JupyterLab extension. We are in the process of porting these tools to CrossCompute Platform 5.
    asset_uri: https://crosscompute.net
  - name_text: Try CrossCompute Analytics SDK 0.9.4
    description_text: The latest version of our software development kit brings enhancements to help you automate reports and increase the expressiveness of your forms. Live PDF preview updates the PDF print in real-time as you save changes to configuration files, notebook scripts, markdown templates and CSS styles. Conditional templates let you make step-by-step wizards by exposing different templates depending on the user's responses to questions. File uploads let users upload files to your scripts for each input variable that is set to file view.
    asset_uri: https://forum.crosscompute.com/t/crosscompute-0-9-4-release-notes-migration-guide/186
    video_slug: B7of7dQVJwM
    playlist_slug: PLxVFbAKDmXyCHKkqT0ucma-Sco9snEMoQ
  - name_text: Try CrossCompute Platform 3
    description_text: CrossCompute Platform 3 was completed in 2021 and featured specialized views for editing geospatial data, including electricity distribution networks. We are in the process of porting these tools to CrossCompute Platform 5.
    asset_uri: https://crosscompute.com/authentications
  - name_text: Try CrossCompute Platform 2
    description_text: CrossCompute Platform 2 was completed in 2016 and featured tool development and deployment directly from Jupyter Notebook. Some features may be broken at this time. We are in the process of porting these tools to CrossCompute Platform 5.
    asset_uri: https://legacy.crosscompute.com/learn

links:
  - name_text: Forum
    description_text: Answers to questions
    asset_uri: https://forum.crosscompute.com
  - name_text: YouTube
    description_text: Updates and demos
    asset_uri: https://www.youtube.com/crosscompute
  - name_text: GitHub
    description_text: Our code repositories
    asset_uri: https://github.com/crosscompute
