---
language_code: en-US

brand:
  image_uri: assets/LogoBrand-Horizontal-20230501.svg
  asset_uri: https://crosscompute.com

title_text: CrossCompute - Deploy Servers, Upload Tools, Control Access

description_text: Don't Let Hackers Wreak Havoc on Your Customers! Deploy Your Tools on Secure Private Servers. CrossCompute is a customizable platform for running tools. Our SDK and platform simplify the process of distributing web-based tools, with a focus on access security.

headline_text: Don't Let Hackers Wreak Havoc on Your Customers!

pitch_text: Deploy Your Tools on Secure Private Servers

pitch_markdown: |

  ### Deploy Servers, Upload Tools, Control Access

  CrossCompute is a customizable platform for running tools. Our SDK and platform simplify the process of distributing web-based tools, with a focus on access security.

updates:
  - name_text: Electric Distribution Outage Statistics for Operations Managers
    description_text: Use historical data to see where, when and why unplanned outages are happening.
    asset_uri: https://forum.crosscompute.com/t/electric-distribution-outage-statistics-for-operations-managers/245
    extra_html: <div class="_spotlight"><img class="_hidden" loading="lazy" data-src="https://forum.crosscompute.com/uploads/default/original/1X/cb1290f4765815c2e464b78175a5ae6952d814db.gif"></div>
  - name_text: Suggest a Tool
    description_text: CrossCompute Platform 5.1.0 is now live! What tools would you like to see?
    asset_uri: https://crosscompute.com/t/suggest-tool
  - name_text: Launch Machine for Pair Programming Command Line
    description_text: Start a pair programming session with your team.
    asset_uri: https://crosscompute.com/t/pair-program
  - name_text: Try CrossCompute Platform 4
    description_text: CrossCompute Platform 4 was completed in 2023 and featured tools for testing our CrossCompute Analytics SDK, including our custom JupyterLab extension.
    asset_uri: https://crosscompute.net
  - name_text: Try CrossCompute Analytics SDK 0.9.4
    description_text: The latest version of our software development kit brings enhancements to help you automate reports and increase the expressiveness of your forms. Live PDF preview updates the PDF print in real-time as you save changes to configuration files, notebook scripts, markdown templates and CSS styles. Conditional templates let you make step-by-step wizards by exposing different templates depending on the user's responses to questions. File uploads let users upload files to your scripts for each input variable that is set to file view.
    asset_uri: https://forum.crosscompute.com/t/crosscompute-0-9-4-release-notes-migration-guide/186
    extra_html: <iframe class="_hidden _video" loading="lazy" width="560" height="315" data-src="https://www.youtube.com/embed/B7of7dQVJwM?listType=playlist&list=PLxVFbAKDmXyCHKkqT0ucma-Sco9snEMoQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  - name_text: Try CrossCompute Platform 3
    description_text: CrossCompute Platform 3 was completed in 2021 and featured specialized views for editing geospatial data, including electricity distribution networks.
    asset_uri: https://crosscompute.com/authentications
  - name_text: Try CrossCompute Platform 2
    description_text: CrossCompute Platform 2 was completed in 2016 and featured tool development and deployment directly from Jupyter Notebook.
    asset_uri: https://legacy.crosscompute.com/learn

links:
  - name_text: Forum
    description_text: Answers to questions
    asset_uri: https://forum.crosscompute.com
  - name_text: YouTube
    description_text: Updates and demos
    asset_uri: https://www.youtube.com/crosscompute
  - name_text: GitHub
    description_text: Our code repositories
    asset_uri: https://github.com/crosscompute
