---
language_code: en-US

title_text: "CrossCompute | Maximize Your Script's Impact: Create an App Now!"
description_text: Don't let your script go to waste. Make your script useful to more people by turning it into a user-friendly web app. With a few steps, you can turn it into a powerful web app that can automate repetitive tasks, streamline processes and make your life easier. Our products and services make it easy to create a web app from your script, so why wait? Don't miss the opportunity to maximize the potential of your script. Take your script to the web and start seeing the benefits today. CrossCompute specializes in building web apps for gathering, processing and presenting data. We created the CrossCompute Analytics Software Development Kit, an open source package that turns scripts into web apps. Unleash the full potential of your script by turning it into a web app!

brand:
  image_uri: assets/LogoBrand-Horizontal-20230501.svg
  asset_uri: https://crosscompute.com

headline_text: "Maximize Your Script's Impact: Create an App Now!"

action_text: Subscribe to our monthly newsletter

pitch_markdown: |
  Who would benefit from your scripts if they were apps instead?

  Do you have the time and budget to make apps from scratch?

  How can you capture your expertise into apps that non-experts can use?

  Don't let your script go to waste. Make your script useful to more people by turning it into a user-friendly web app. With a few steps, you can turn it into a powerful web app that can automate repetitive tasks, streamline processes and make your life easier. [Our products and services make it easy to create a web app from your script, so why wait?](#services) Don't miss the opportunity to maximize the potential of your script. Take your script to the web and start seeing the benefits today.

  CrossCompute specializes in building web apps for gathering, processing and presenting data. We created the [CrossCompute Analytics Software Development Kit](https://pypi.org/project/crosscompute-analytics), an open source package that turns scripts into web apps. Unleash the full potential of your script by turning it into a web app!

services_markdown: |
  Our products and services are designed for organizations that collect data, run analyses and publish reports on a periodic basis.

  The [CrossCompute Analytics Software Development Kit](https://pypi.org/project/crosscompute-analytics) drastically reduces the time and effort needed to update a software as a service (SaaS) solution directly from your command-line scripts and Jupyter notebooks. [See how an organization is using CrossCompute to automate reports for electric utilities](https://www.python.org/success-stories/python-powered-crosscompute-report-automation-for-ereliability-tracker-leads-to-cost-and-time-savings-for-the-american-public-power-association-updated-20210526-0900).

  Here are services we provide:

  - Turn existing scripts into web apps
  - Transform spreadsheets and forms into step by step wizards
  - Automate analyses so that non-experts can generate reports from new data

  Our expertise is in automating the analysis of spatial data and imagery to support infrastructure planning. By partnering with us, you can leverage our expertise in building pipelines for geospatial information processing.

pricing_markdown: |
  ### Option 1: Create Your Own Apps

  - Host Your Apps on [crosscompute.net](https://crosscompute.net)
  - No Upfront Cost
  - 20% Revenue Share

  ### Option 2: Power Your Organization

  - Host Your Apps on Managed Servers
  - $10k Per Year
  - Training and Support Add-Ons

updates:
  - name: Production Tracking System
    description: Track production times for product manufacturing
    video_uri: https://youtu.be/rKM6YPrkGTk
    asset_uri: https://crosscompute.net/a/launch-production-tracking-system
  - name: Development Server in JupyterLab
    description: Experiment with the code behind our example widgets
    video_uri: https://youtu.be/RGvs9spyZy8
    asset_uri: https://crosscompute.net/a/learn-examples-in-jupyterlab
  - name: Airport Traffic Dashboard
    description: See how much time it takes to get to the airport
    asset_uri: https://crosscompute.net/a/see-airport-traffic
  - name: Internet Speed Form
    description: Record your internet speed on a map
    asset_uri: https://crosscompute.net/a/report-internet-speed

requests:
  - name: Example Request
    asset_uri: https://example.com

internal_links:
  - name: Forum
    description: Read tutorials and ask questions
    asset_uri: https://forum.crosscompute.com
  - name: Documentation
    description: Learn how to use our open source packages
    asset_uri: https://docs.crosscompute.com
  - name: Platform v4
    description: Gallery of widgets built using our open source framework
    video_uri: https://www.youtube.com/shorts/5g782ny0zqo
    asset_uri: https://crosscompute.net
  - name: Platform v3
    description: Analytics prototype featuring an electricity network editor
    video_uri: https://youtu.be/XyXwg9Z9e_E
    asset_uri: https://crosscompute.com/authentications
  - name: Platform v2
    description: Tools created by users with Jupyter Notebook
    video_uri: https://youtu.be/M6GPVq3-Beg
    asset_uri: https://crosscompute.com/learn
  - name: Algorithm Cookbooks
    description: Selection of tools for electricity planning
    asset_uri: https://v2.crosscompute.com/cookbooks

external_links:
  - name: GitHub
    asset_uri: https://github.com/crosscompute
  - name: YouTube
    asset_uri: https://www.youtube.com/crosscompute
  - name: Twitter
    asset_uri: https://twitter.com/crosscompute
  - name: LinkedIn
    asset_uri: https://www.linkedin.com/company/crosscompute
  - name: Facebook
    asset_uri: https://www.facebook.com/crosscompute
  - name: Tumblr
    asset_uri: https://crosscompute.tumblr.com
  - name: Discord
    asset_uri: https://discord.com/channels/905104835639140393/905104836104691843
  - name: Twitch
    asset_uri: https://twitch.tv/crosscompute
  - name: EventBrite
    asset_uri: https://www.eventbrite.com/o/crosscompute-15688825369

accomplishments:
  - description: Algorithms for microgrid site selection used to raise $5m for microgrid developer in Africa
    asset_uri: https://crosscompute.net/a/place-microgrids
  - description: Algorithms for placing electricity poles and lines used to plan $240m for microgrid developer in Southeast Asia
    asset_uri: https://youtu.be/smcgvgrERV0
  - description: Web based decision support tool used to draft electrification plans for 12+ countries in Africa, Southeast Asia and Central America
    asset_uri: https://crosscompute.com/r/J7qzpkPoiwO3wcsihD6jx6HsAFBKIhTm
  - description: Web app for tracking outages being used by 500+ utilities
    asset_uri: https://www.publicpower.org/reliability-tracking
  - description: Web app for mapping electricity distribution networks
    asset_uri: https://youtu.be/CUJ3u_I282o
  - description: Algorithms for finding buildings in satellite images
    asset_uri: https://github.com/invisibleroads/find-buildings-cuda-convnet
  - description: Report automation system used for electricity outage benchmarking
    asset_uri: https://www.python.org/success-stories/python-powered-crosscompute-report-automation-for-ereliability-tracker-leads-to-cost-and-time-savings-for-the-american-public-power-association-updated-20210526-0900

acknowledgments:
  - name: Olga Ryabtseva
    asset_uri: https://www.linkedin.com/in/olga-creutzburg-52a689b2
  - name: Salah Ahmed
    asset_uri: https://www.linkedin.com/in/salahspage
  - name: Cathaleen Kaiyoorawongs
    asset_uri: https://www.linkedin.com/in/catalina-kaiyoorawongs
  - name: Roy Hyunjin Han
    asset_uri: https://www.linkedin.com/in/invisibleroads
  - name: Rodrigo Guarachi
    asset_uri: https://www.linkedin.com/in/rmguarachi
  - name: Marta Moreno Catalan
    asset_uri: https://www.linkedin.com/in/marta-moreno-07364b82
  - name: Kashfi Fahim
    asset_uri: https://www.linkedin.com/in/kashfifahim
  - name: Miguel Ángel Gordián
    asset_uri: https://github.com/zoek1
  - name: Polina Chernomaz
    asset_uri: https://www.linkedin.com/in/polinac
  - name: Samuel Edandison
    asset_uri: https://www.linkedin.com/in/edandison
  - name: Ning Wei
    asset_uri: https://www.linkedin.com/in/ning-wei-8152393b
  - name: Eugen Fomenko
    asset_uri: https://www.linkedin.com/in/eugen-fomenko-57b204168
  - name: Noé Domínguez Porras
    asset_uri: https://www.linkedin.com/in/noedominguez
  - name: Mary Rodriguez Gort
    asset_uri: https://theorg.com/org/tampa-bay-innovation-center/org-chart/mary-rodriguez-gort
  - name: Ken Evans
    asset_uri: https://www.linkedin.com/in/evansken
  - name: Alex Hofmann
    asset_uri: https://www.linkedin.com/in/alex-hofmann-4a006519
  - name: Ji Yoon Lee
    asset_uri: https://www.linkedin.com/in/ji-yoon-lee-516750136
  - name: Tyler Doyle
    asset_uri: https://www.linkedin.com/in/tyler-doyle-987642111
  - name: Ethan Epstein
    asset_uri: https://www.linkedin.com/in/ethan-epstein-80772093
  - name: Jennifer Ruda
    asset_uri: https://www.linkedin.com/in/jruda
  - name: Shaky Sherpa
    asset_uri: https://www.linkedin.com/in/shakythesherpa
  - name: Trevor David Rhone
    asset_uri: https://www.linkedin.com/in/trevor-david-rhone-965ba9b
  - name: Matt Henning
    asset_uri: https://www.linkedin.com/in/matthew-henning-26406412b
  - name: Elizabeth Ritter
    asset_uri: https://www.linkedin.com/in/elizabeth-b-ritter
  - name: Chenxin Han
    asset_uri: https://www.linkedin.com/in/chenxin-han
  - name: Soo Ji Choi
    asset_uri: https://www.linkedin.com/in/susie-choi-0504
  - name: Yao Kou
    asset_uri: https://www.linkedin.com/in/yaokou
  - name: Ying Zhou
    asset_uri: https://www.linkedin.com/in/yingznyc
  - name: Margarita Zias
    asset_uri: https://www.linkedin.com/in/margarita-zias
  - name: Elaine Chan
    asset_uri: https://www.linkedin.com/in/chanelaine
  - name: Aida Shoydokova
    asset_uri: https://www.linkedin.com/in/ashoydok
  - name: Lauren Talbot
    asset_uri: https://www.linkedin.com/in/laurentalbotnyc
  - name: Benjamin Dean
    asset_uri: https://www.linkedin.com/in/benwdean
  - name: Catherine Kwan
    asset_uri: https://www.linkedin.com/in/catherine-kwan-27aba827
  - name: Nicholas O'Brien
    asset_uri: https://www.linkedin.com/in/njobrien
  - name: Michael Flowers
    asset_uri: https://www.linkedin.com/in/michael-flowers-8b61601b
  - name: Ewa Jodlowska
    asset_uri: https://www.linkedin.com/in/ewa-jodlowska-39810611
  - name: Betsy Waliszewski
    asset_uri: https://www.linkedin.com/in/betsywaliszewski
  - name: Selin Kocaman
    asset_uri: https://www.linkedin.com/in/ayse-selin-kocaman-473023a
  - name: Matt Basinger
    asset_uri: https://www.linkedin.com/in/matt-basinger-a7b14b35
  - name: Dorcas Murai
    asset_uri: https://www.linkedin.com/in/dorcas-murai-119813114
  - name: Christopher Horner
    asset_uri: https://www.linkedin.com/in/christopher-hornor-480a913
  - name: Liliana Durán
    asset_uri: https://www.linkedin.com/in/lumiservicioslilianaduran
  - name: Ariana Gradow
    asset_uri: https://www.linkedin.com/in/arianagradow
  - name: Rajesh Menon
    asset_uri: https://www.linkedin.com/in/rmeno
  - name: Jessica Leon
    asset_uri: https://www.linkedin.com/in/jesleon
  - name: Diego Saenz
    asset_uri: https://www.linkedin.com/in/diegosaenz2010
  - name: Paul Everitt
    asset_uri: https://www.linkedin.com/in/paeveritt
  - name: Jake Maslow
    asset_uri: https://www.linkedin.com/in/jake-maslow-4580106
  - name: Susan Kum
    asset_uri: https://www.linkedin.com/in/susan-s-kum
  - name: Chris Natali
    asset_uri: https://www.linkedin.com/in/chris-natali-6841472b
  - name: Edwin Adkins
    asset_uri: https://www.linkedin.com/in/edwin-adkins
  - name: Aly Sanoh
    asset_uri: https://www.linkedin.com/in/sanohaly
  - name: Vijay Modi
    asset_uri: https://www.linkedin.com/in/vijay-modi-39241229
  - name: Tampa Bay Innovation Center
    asset_uri: https://tbinnovates.com
  - name: Python Software Foundation
    asset_uri: https://python.org/psf
  - name: DevLabs México
    asset_uri: https://www.devlabs.com.mx
  - name: American Public Power Association
    asset_uri: https://publicpower.org
  - name: U.S. Department of Energy
    asset_uri: https://www.energy.gov
  - name: Quadracci Sustainable Engineering Lab at Columbia University
    asset_uri: https://qsel.columbia.edu
  - name: Tech Incubator at Queens College
    asset_uri: https://techincubatorqc.com
  - name: World Bank
    asset_uri: https://www.worldbank.org
  - name: NYC Mayor's Office of Data Analytics
    asset_uri: https://nyc.gov/analytics
