---
language_code: en-US

brand:
  image_uri: assets/LogoBrand-Horizontal-20230501.svg
  asset_uri: https://crosscompute.com

title_text: CrossCompute | Host Runnable Tools

headline_text: Host Runnable Tools

description_text: Let people run your tools online. CrossCompute is a library of tools that you can run online. We help you host your own tools. We created the CrossCompute Analytics Software Development Kit, an open source package that turns scripts into web-based tools. Host your tools on separate servers that we manage for you on your own domain. Distribute scripts as web-based tools within your organization using the CrossCompute Analytics Automation System.

demo_slug: B7of7dQVJwM

pitch_markdown: |
  Let people run your tools online.

  CrossCompute is a [library of tools](https://crosscompute.net) that you can run online. We help you host your own tools. We created the CrossCompute Analytics Software Development Kit, an open source package that turns scripts into web-based tools.

services_markdown: |
  ### Option 1: Host your tools on [crosscompute.net](https://crosscompute.net)

  - Host your scripts as web-based tools online
  - Earn subscription revenue from your tools

  ### Option 2: Host your tools on your own domain

  - Distribute scripts as web-based tools within your organization using the CrossCompute Analytics Automation System
  - Host your tools on separate servers that we manage on your own domain for $8,400 per year

updates:
  - name_text: Try CrossCompute Analytics SDK 0.9.4
    description_text: The latest version of our software development kit brings enhancements to help you automate reports and increase the expressiveness of your forms. Live PDF preview updates the PDF print in real-time as you save changes to configuration files, notebook scripts, markdown templates and CSS styles. Conditional templates let you make step-by-step wizards by exposing different templates depending on the user's responses to questions. File uploads let users upload files to your scripts for each input variable that is set to file view.
    video_uri: https://youtu.be/B7of7dQVJwM
    asset_uri: https://forum.crosscompute.com/t/crosscompute-0-9-4-release-notes-migration-guide/186

sessions_markdown: |
  <div class="calendly-inline-widget" data-url="https://calendly.com/crosscompute/teamwork?hide_event_type_details=1&hide_gdpr_banner=1"></div>
  <script src="https://assets.calendly.com/assets/external/widget.js" async></script>
  To schedule a teamwork session, use the calendar above.

links:
  - name_text: Forum
    description_text: Tutorials and questions
    asset_uri: https://forum.crosscompute.com
  - name_text: YouTube
    description_text: Tutorials and demos
    asset_uri: https://www.youtube.com/crosscompute
  - name_text: GitHub
    description_text: Our code repositories
    asset_uri: https://github.com/crosscompute
  - name_text: Documentation
    description_text: Reference on how to use the CrossCompute Analytics Software Development Kit
    asset_uri: https://docs.crosscompute.com
