---
language_code: en-US

brand:
  image_uri: assets/LogoBrand-Horizontal-20230501.svg
  asset_uri: https://crosscompute.com

title_text: CrossCompute | Runnable Tools

description_text: Protect expertise before experts leave your team. What would happen to your company if your best analysts were hit by a truck? CrossCompute works with your team to convert institutional knowledge into processes and tools that can be shared and scaled across departments. Even when key personnel disappear, CrossCompute ensures that tools and the knowledge embedded in them remain accessible and up-to-date, so that your operations can continue. Rank your company's reports. Take inventory of the scripts and datasets used to draft the reports. Turn the scripts into tools that non-technical people can run. Share the tools to boost data-driven decisions across your organization.

headline_text: Protect Expertise Before Experts Leave Your Team

pitch_text: What Would Happen to Your Company If Your Best Analysts Were Hit By a Truck?

pitch_markdown: |

  CrossCompute works with your team to convert institutional knowledge into processes and tools that can be shared and scaled across departments.

  Even when key personnel disappear, CrossCompute ensures that tools and the knowledge embedded in them remain accessible and up-to-date, so that your operations can continue.

  - Step 1: Rank your company's reports
  - Step 2: Take inventory of the scripts and datasets used to draft the reports
  - Step 3: Turn the scripts into tools that non-technical people can run
  - Step 4: Share the tools to boost data-driven decisions across your organization

  If your company does not have existing scripts or spreadsheets coded by programmer analysts or data scientists, then our solution is probably not the right fit for you.

action_text: Are You Ready to Future Proof Your Analytics?

action_markdown: |

  <iframe src="https://crosscompute.net/a/subscribe-newsletter?_embed"></iframe>

  Enter your email to subscribe to our newsletter or schedule a consultation using the calendar.

  <div class="calendly-inline-widget" data-url="https://calendly.com/crosscompute/teamwork?hide_event_type_details=1&hide_gdpr_banner=1"></div>
  <script src="https://assets.calendly.com/assets/external/widget.js" async></script>

updates:
  - name_text: Try CrossCompute Analytics SDK 0.9.4
    description_text: The latest version of our software development kit brings enhancements to help you automate reports and increase the expressiveness of your forms. Live PDF preview updates the PDF print in real-time as you save changes to configuration files, notebook scripts, markdown templates and CSS styles. Conditional templates let you make step-by-step wizards by exposing different templates depending on the user's responses to questions. File uploads let users upload files to your scripts for each input variable that is set to file view.
    video_uri: https://youtu.be/B7of7dQVJwM
    asset_uri: https://forum.crosscompute.com/t/crosscompute-0-9-4-release-notes-migration-guide/186

links:
  - name_text: Forum
    description_text: Tutorials and questions
    asset_uri: https://forum.crosscompute.com
  - name_text: YouTube
    description_text: Tutorials and demos
    asset_uri: https://www.youtube.com/crosscompute
  - name_text: GitHub
    description_text: Our code repositories
    asset_uri: https://github.com/crosscompute
