---
language_code: en-US

brand:
  image_uri: assets/LogoBrand-Horizontal-20230501.svg
  asset_uri: https://crosscompute.com

title_text: CrossCompute | Host Runnable Scripts

headline_text: Host Runnable Scripts

description_text: CrossCompute is a library of scripts that you can run online. We help people host their own scripts. We created the CrossCompute Analytics Software Development Kit, an open source package that turns scripts into apps.

demo_slug: B7of7dQVJwM

pitch_markdown: |
  Let people run your scripts online.

  CrossCompute is a [library of scripts](https://crosscompute.net) that you can run online. We help people host their own scripts. We created the CrossCompute Analytics Software Development Kit, an open source package that turns scripts into apps.

services_markdown: |
  ### Option 1: Host your scripts on [crosscompute.net](https://crosscompute.net)
  
  - Host your scripts for free
  - Earn subscription revenue from your scripts

  ### Option 2: Host your scripts on your own domain

  - Host your scripts on separate servers that we manage for you on your own domain
  - Pay a fixed price of $8,400 for one year of managed servers to develop and distribute apps using the CrossCompute Analytics Automation System within your organization

updates:
  - name_text: Try CrossCompute Analytics SDK 0.9.4
    description_text: The latest version of our software development kit brings enhancements to help you automate reports and increase the expressiveness of your forms. Live PDF preview updates the PDF print in real-time as you save changes to configuration files, notebook scripts, markdown templates and CSS styles. Conditional templates lets you make step-by-step wizards by exposing different templates depending on the user's responses to questions. File uploads let users upload files to your scripts if you set an input variable to file view.
    video_uri: https://youtu.be/B7of7dQVJwM
    asset_uri: https://forum.crosscompute.com/t/crosscompute-0-9-4-release-notes-migration-guide/186

sessions_markdown: |
  To schedule a teamwork session, use the calendar below.
  <div class="calendly-inline-widget" data-url="https://calendly.com/crosscompute/teamwork?hide_event_type_details=1&hide_gdpr_banner=1" style="height:700px"></div>
  <script src="https://assets.calendly.com/assets/external/widget.js" async></script>

links:
  - name_text: Forum
    description_text: Tutorials and frequently asked questions
    asset_uri: https://forum.crosscompute.com
  - name_text: GitHub
    description_text: Our open source code repositories
    asset_uri: https://github.com/crosscompute
  - name_text: YouTube
    description_text: Videos of tutorials and demos
    asset_uri: https://www.youtube.com/crosscompute
  - name_text: Documentation
    description_text: Reference on how to use the CrossCompute Analytics Software Development Kit
    asset_uri: https://docs.crosscompute.com
