---
language_code: en-US

brand:
  image_uri: assets/LogoBrand-Horizontal-20230501.svg
  asset_uri: https://crosscompute.com

title_text: CrossCompute | Tools for Technical Trainers

description_text: For instructors who use Jupyter Notebooks to teach Software Programming, Data Analytics and Cybersecurity -- provide better student experiences in less time! CrossCompute will deploy a secure cloud-based training environment for your corporate workshop, conference tutorial or university class, test your course content for typos and bugs and develop custom pedagogical tools to improve learning outcomes.

headline_text: Provide Better Student Experiences in Less Time

pitch_text: For Instructors who use Jupyter Notebooks to teach Software Programming, Data Analytics and Cybersecurity

pitch_markdown: |

  ### Secure Cloud-Based Training Environments
  Handle hundreds of concurrent JupyterLab sessions in your Corporate Workshops, Conference Tutorials and University Classes.

  ### Course Content Testing
  Let us check for typos and bugs in your Jupyter Notebooks.

  ### Pedagogical Tools to Improve Learning Outcomes
  We can make custom tools and exercises to reinforce concepts in your course using our open source CrossCompute Analytics Software Development Kit.

action_markdown: |

  <div class="calendly-inline-widget" data-url="https://calendly.com/crosscompute/teamwork?hide_event_type_details=1&hide_gdpr_banner=1"></div>
  <script src="https://assets.calendly.com/assets/external/widget.js" async></script>

updates:
  - name_text: Expect CrossCompute Platform 5.0.0
    description_text: We have been actively developing the next version of our platform for the past year. Expect a launch in August 2024.
  - name_text: Try CrossCompute Analytics SDK 0.9.4
    description_text: The latest version of our software development kit brings enhancements to help you automate reports and increase the expressiveness of your forms. Live PDF preview updates the PDF print in real-time as you save changes to configuration files, notebook scripts, markdown templates and CSS styles. Conditional templates let you make step-by-step wizards by exposing different templates depending on the user's responses to questions. File uploads let users upload files to your scripts for each input variable that is set to file view.
    asset_uri: https://forum.crosscompute.com/t/crosscompute-0-9-4-release-notes-migration-guide/186
    video_slug: B7of7dQVJwM
    playlist_slug: PLxVFbAKDmXyCHKkqT0ucma-Sco9snEMoQ

links:
  - name_text: Forum
    description_text: Answers to questions
    asset_uri: https://forum.crosscompute.com
  - name_text: YouTube
    description_text: Updates and demos
    asset_uri: https://www.youtube.com/crosscompute
  - name_text: GitHub
    description_text: Our code repositories
    asset_uri: https://github.com/crosscompute
